#!/usr/bin/python


'''
	UAS SERVER
'''
UAS_SERVER_IP			=	"192.168.0.12"
UAS_SERVER_IP_0			=	UAS_SERVER_IP
UAS_SERVER_IP_1			=	UAS_SERVER_IP

UAS_SERVER_PORT_00		=	"10000"
UAS_SERVER_PORT_01		=	"40000"
UAS_SERVER_PORT_10		=	"20000"
UAS_SERVER_PORT_11		=	"50000"

UAS_SERVER_USER_0		=	"server0"
UAS_SERVER_USER_1		=	"server1"

UAS_SERVER_FILE_0		=	"uas-0.xml"
UAS_SERVER_FILE_1		=	"uas-1.xml"
UAS_SERVER_REGISTER_FILE_0	=	"register.xml"
UAS_SERVER_REGISTER_FILE_1	=	"register.xml"
UAS_SERVER_UNREGISTER_FILE_0	=	"unregister.xml"
UAS_SERVER_UNREGISTER_FILE_1	=	"unregister.xml"

UAS_SERVER_BASE_DIR		=	"xml/"


'''
	UAC CLIENTs
'''
UAC_CLIENT_IP_0			=	"192.168.0.11"
UAC_CLIENT_IP_1			=	"192.168.0.15"

UAC_CLIENT_PORT_00		=	"11111"
UAC_CLIENT_PORT_01		=	"44444"
UAC_CLIENT_PORT_10		=	"22222"
UAC_CLIENT_PORT_11		=	"55555"

UAC_CLIENT_USER_0		=	"client0"
UAC_CLIENT_USER_1		=	"client1"

UAC_CLIENT_FILE_0		=	"uac-0.xml"
UAC_CLIENT_FILE_1		=	"uac-1.xml"
UAC_CLIENT_REGISTER_FILE_0	=	"register.xml"
UAC_CLIENT_REGISTER_FILE_1	=	"register.xml"
UAC_CLIENT_UNREGISTER_FILE_0	=	"unregister.xml"
UAC_CLIENT_UNREGISTER_FILE_1	=	"unregister.xml"

UAC_CLIENT_BASE_DIR		=	"xml/"


'''
	KAMAILIO SERVER
'''
KAMAILIO_SERVER_IP		=	"192.168.0.14"
KAMAILIO_SERVER_PORT		=	"5060"


'''
	others
'''
TWIN_PORT			=	"9999"	# 3pcc twin port
