#!/usr/bin/python

'''
    GENERAL
'''
SERVER_IF = "eth1"
SERVER_IP = "192.168.0.16"

SERVER_PORT_00 = "10000"
SERVER_PORT_01 = "40000"
SERVER_PORT_10 = "20000"
SERVER_PORT_11 = "50000"

SERVER_ID = "99"

CLIENT_IF_0 = "wlan0"
CLIENT_IF_1 = "wlan1"

CLIENT_IP_0 = "192.168.0.11"
CLIENT_IP_1 = "192.168.0.14"

CLIENT_PORT_00 = "11111"
CLIENT_PORT_01 = "44444"
CLIENT_PORT_10 = "22222"
CLIENT_PORT_11 = "55555"

CLIENT_ID_0 = "0"
CLIENT_ID_1 = "1"

SIP_PROTO= "sip"
SIPS_PROTO= "sips"

'''
    simple
'''
# SIP
SIP_SERVER0_IF = SERVER_IF
SIP_SERVER0_IP = SERVER_IP
SIP_SERVER0_PORT = SERVER_PORT_00

SIP_SERVER0_ID = SERVER_ID

SIP_CLIENT0_IF = CLIENT_IF_0
SIP_CLIENT0_IP = CLIENT_IP_0
SIP_CLIENT0_PORT = CLIENT_PORT_00

SIP_CLIENT0_ID = CLIENT_ID_0

# RTP
RTP_SERVER0_IF = SERVER_IF
RTP_SERVER0_IP = SERVER_IP
RTP_SERVER0_PORT = SERVER_PORT_01

RTP_CLIENT0_IF = CLIENT_IF_0
RTP_CLIENT0_IP = CLIENT_IP_0
RTP_CLIENT0_PORT = CLIENT_PORT_01


'''
    3pcc
'''
SIP_3PCC_TWIN_PORT = "9999"

# SIP
SIP_3PCC_SERVER0_IF = SERVER_IF
SIP_3PCC_SERVER0_IP = SERVER_IP
SIP_3PCC_SERVER0_PORT = SERVER_PORT_00

SIP_3PCC_SERVER1_IF = SERVER_IF
SIP_3PCC_SERVER1_IP = SERVER_IP
SIP_3PCC_SERVER1_PORT = SERVER_PORT_10

SIP_3PCC_SERVER0_ID = SERVER_ID
SIP_3PCC_SERVER1_ID = SERVER_ID

SIP_3PCC_CLIENT0_IF = CLIENT_IF_0
SIP_3PCC_CLIENT0_IP = CLIENT_IP_0
SIP_3PCC_CLIENT0_PORT = CLIENT_PORT_00

SIP_3PCC_CLIENT1_IF = CLIENT_IF_1
SIP_3PCC_CLIENT1_IP = CLIENT_IP_1
SIP_3PCC_CLIENT1_PORT = CLIENT_PORT_10

SIP_3PCC_CLIENT0_ID = CLIENT_ID_0
SIP_3PCC_CLIENT1_ID = CLIENT_ID_1

# RTP
RTP_3PCC_SERVER0_IF = SERVER_IF
RTP_3PCC_SERVER0_IP = SERVER_IP
RTP_3PCC_SERVER0_PORT = SERVER_PORT_01

RTP_3PCC_SERVER1_IF = SERVER_IF
RTP_3PCC_SERVER1_IP = SERVER_IP
RTP_3PCC_SERVER1_PORT = SERVER_PORT_11

RTP_3PCC_CLIENT0_IF = CLIENT_IF_0
RTP_3PCC_CLIENT0_IP = CLIENT_IP_0
RTP_3PCC_CLIENT0_PORT = CLIENT_PORT_01

RTP_3PCC_CLIENT1_IF = CLIENT_IF_1
RTP_3PCC_CLIENT1_IP = CLIENT_IP_1
RTP_3PCC_CLIENT1_PORT = CLIENT_PORT_11

# SIP users
SIP_3PCC_CLIENT0_USER = "client0"
SIP_3PCC_CLIENT1_USER = "client1"
SIP_3PCC_SERVER0_USER = "server0"
SIP_3PCC_SERVER1_USER = "server1"

SIPP_3PCC_CLIENT0_FILE = "0-3pcc-uac.xml"
SIPP_3PCC_CLIENT1_FILE = "1-3pcc-uac.xml"
SIPP_3PCC_SERVER0_FILE = "0-3pcc-uas.xml"
SIPP_3PCC_SERVER1_FILE = "1-3pcc-uas.xml"
SIPP_3PCC_BASE_DIR = "xml/"

# SIPp
SIPP_SERVER0_FILE = "uas.xml"
SIPP_CLIENT0_FILE = "uac.xml"

SIPP_BASE_DIR = "xml/"


'''
    SIPP UAC related
'''
#UAC_IF_CONNECT = INTERFACE0
#UAC_HW_CONNECT = helps.get_hw_addr(UAC_IF_CONNECT)
#UAC_IP_CONNECT = helps.get_ip_addr(UAC_IF_CONNECT)

UAC_PORT_CONNECT = 5060
UAC_PORT_CONTROL = 8889

UAC_MSG_NR          = 100       # total calls
UAC_MSG_RATE        = 10        # calls per
UAC_MSG_RATEP       = 1000      # milisecond

UAC_INVITE_FILE     = "uac_invite.xml"
UAC_REINVITE_FILE   = "uac_reinvite.xml"
UAC_BYE_FILE        = "uac_bye.xml"
UAC_REFER_FILE      = "uac_refer.xml"


'''
    SIPP UAS related
'''
#UAS_IF_CONNECT = INTERFACE1
#UAS_HW_CONNECT = helps.get_hw_addr(UAS_IF_CONNECT)
#UAS_IP_CONNECT = helps.get_ip_addr(UAS_IF_CONNECT)

UAS_PORT_CONNECT = 5060
UAS_PORT_CONTROL = 8888

UAS_FILE = "uas.xml"


'''
    SIPSAK related
'''
SIPSAK_BASE_CALLS       = 100       # total of 1000 calls
SIPSAK_BASE_PORT        = 9999      # starting port
SIPSAK_BASE_NUMBER      = "number"  # user name used for appending

SIPSAK_BASE_DIR         = "msg/"
SIPSAK_BYE_FILE         = "bye.msg"
SIPSAK_INVITE_FILE      = "invite.msg"
SIPSAK_REINVITE_FILE    = "reinvite.msg"
